import { dummyPHCs } from '@/dummy/phcs';
import { dummyAttendance } from '@/dummy/attendance';
import { dummyMedicines } from '@/dummy/medicines';
import { dummyAlerts } from '@/dummy/alerts';
import { dummyNotifications } from '@/dummy/notifications';
import { dummyReports } from '@/dummy/reports';
import { dummyDistrict } from '@/dummy/district';
import { PHC } from '@/shared/types/phc';
import { AttendanceRecord } from '@/shared/types/attendance';
import { MedicineStock } from '@/shared/types/medicine';
import { AlertItem } from '@/shared/types/alert';
import { NotificationItem } from '@/shared/types/notification';
import { ReportItem } from '@/shared/types/report';
import { AIRecommendation } from '@/shared/types/ai';

export let localPHCs = JSON.parse(JSON.stringify(dummyPHCs)) as PHC[];
export let localAttendance = JSON.parse(JSON.stringify(dummyAttendance)) as AttendanceRecord[];
export let localMedicines = JSON.parse(JSON.stringify(dummyMedicines)) as MedicineStock[];
export let localAlerts = JSON.parse(JSON.stringify(dummyAlerts)) as AlertItem[];
export let localNotifications = JSON.parse(JSON.stringify(dummyNotifications)) as NotificationItem[];
export let localReports = JSON.parse(JSON.stringify(dummyReports)) as ReportItem[];
export let localDistrict = { ...dummyDistrict };

// Recommendations generated by AI
export let localRecommendations: AIRecommendation[] = [
  {
    id: 'rec1',
    title: 'Redistribute Dengue Kits',
    sourceFacility: 'phc_dharampur',
    targetFacility: 'phc_kalan',
    item: 'Dengue NS1 Antigen Test Kit',
    quantity: 50,
    confidence: 0.94,
    reasoning: 'Dharampur PHC currently has 300+ excess kits. Rampur Kalan PHC is facing a critical dengue outbreak with only 15 kits remaining.',
    timestamp: new Date().toISOString(),
  },
];

// Active transfers (approved recommendations)
export interface TransferOrder {
  id: string;
  recommendationId?: string;
  sourceFacilityId: string;
  targetFacilityId: string;
  medicineId: string;
  medicineName: string;
  quantity: number;
  status: 'PENDING' | 'EN_ROUTE' | 'DELIVERED';
  timestamp: string;
}

export let localTransfers: TransferOrder[] = [];

// Helper functions to update state
export const updateLocalPHC = (updated: PHC) => {
  localPHCs = localPHCs.map((p) => (p.id === updated.id ? updated : p));
};

export const addLocalAttendance = (record: AttendanceRecord) => {
  localAttendance.push(record);
};

export const updateLocalMedicine = (updated: MedicineStock) => {
  localMedicines = localMedicines.map((m) => (m.id === updated.id ? updated : m));
};

export const updateLocalAlert = (updated: AlertItem) => {
  localAlerts = localAlerts.map((a) => (a.id === updated.id ? updated : a));
};

export const addLocalNotification = (notif: NotificationItem) => {
  localNotifications.unshift(notif);
};

export const addLocalTransfer = (transfer: TransferOrder) => {
  localTransfers.push(transfer);
};

export const updateLocalTransferStatus = (id: string, status: 'PENDING' | 'EN_ROUTE' | 'DELIVERED') => {
  localTransfers = localTransfers.map((t) => (t.id === id ? { ...t, status } : t));
};

export const removeLocalRecommendation = (id: string) => {
  localRecommendations = localRecommendations.filter((r) => r.id !== id);
};
