import { dummyPHCs } from '@/dummy/phcs';
import { dummyAttendance } from '@/dummy/attendance';
import { dummyMedicines } from '@/dummy/medicines';
import { dummyAlerts } from '@/dummy/alerts';
import { dummyNotifications } from '@/dummy/notifications';
import { dummyReports } from '@/dummy/reports';
import { dummyDistrict } from '@/dummy/district';
import { PHC } from '@/shared/types/phc';
import { AttendanceRecord } from '@/shared/types/attendance';
import { MedicineStock } from '@/shared/types/medicine';
import { AlertItem } from '@/shared/types/alert';
import { NotificationItem } from '@/shared/types/notification';
import { ReportItem } from '@/shared/types/report';
import { AIRecommendation } from '@/shared/types/ai';
import { dummyLogistics, LogisticsRequest } from '@/dummy/logistics';
import { dummyDiseaseTrends, DiseaseTrend } from '@/dummy/diseaseTrends';

export let localPHCs = JSON.parse(JSON.stringify(dummyPHCs)) as PHC[];
export let localAttendance = JSON.parse(JSON.stringify(dummyAttendance)) as AttendanceRecord[];
export let localMedicines = JSON.parse(JSON.stringify(dummyMedicines)) as MedicineStock[];
export let localAlerts = JSON.parse(JSON.stringify(dummyAlerts)) as AlertItem[];
export let localNotifications = JSON.parse(JSON.stringify(dummyNotifications)) as NotificationItem[];
export let localReports = JSON.parse(JSON.stringify(dummyReports)) as ReportItem[];
export let localDistrict = { ...dummyDistrict };
export let localLogistics = JSON.parse(JSON.stringify(dummyLogistics)) as LogisticsRequest[];
export let localDiseaseTrends = JSON.parse(JSON.stringify(dummyDiseaseTrends)) as DiseaseTrend[];
export let localTelemetryAudits = [
  { id: 'ta-1', type: 'approved', icon: 'check', color: 'green', text: 'Redistribution Approved', desc: 'DHO Rajesh Kumar approved transfer of 50 Dengue Kits to PHC Badalpur.', time: '10m ago' },
  { id: 'ta-2', type: 'alert', icon: 'alert-triangle', color: 'red', text: 'Critical Stockout Alert', desc: 'Paracetamol stock dropped below 150 tablets at PHC Badalpur.', time: '1h ago' }
];

const dengueBarolaRec = dummyMedicines.find(m => m.facilityId === 'phc_barola' && m.name.includes('Dengue'));
const dengueBadalpurRec = dummyMedicines.find(m => m.facilityId === 'phc_badalpur' && m.name.includes('Dengue'));

// Recommendations generated by AI
export let localRecommendations: AIRecommendation[] = [
  {
    id: 'rec1',
    title: 'Redistribute Dengue Kits',
    sourceFacility: 'phc_barola',
    targetFacility: 'phc_badalpur',
    item: 'Dengue NS1 Antigen Test Kit',
    quantity: 50,
    confidence: 0.94,
    reasoning: `PHC Barola currently has ${dengueBarolaRec?.currentStock || 300} kits in stock. PHC Badalpur is facing a critical dengue outbreak with only ${dengueBadalpurRec?.currentStock || 15} kits remaining.`,
    timestamp: new Date().toISOString(),
  },
  {
    id: 'rec2',
    title: 'Emergency Paracetamol Dispatch',
    sourceFacility: 'chc_bisrakh',
    targetFacility: 'phc_badalpur',
    item: 'Paracetamol 650mg',
    quantity: 200,
    confidence: 0.98,
    reasoning: `PHC Badalpur stock is depleted. CHC Bisrakh has a surplus and can dispatch immediately.`,
    timestamp: new Date().toISOString(),
  },
  {
    id: 'rec3',
    title: 'IV Fluids Reallocation',
    sourceFacility: 'chc_dadri',
    targetFacility: 'chc_bhangel',
    item: 'IV Fluids (NS)',
    quantity: 100,
    confidence: 0.89,
    reasoning: `CHC Bhangel is facing a shortage of Normal Saline. CHC Dadri has 500+ units available.`,
    timestamp: new Date().toISOString(),
  },
  {
    id: 'rec4',
    title: 'Amoxicillin Transfer',
    sourceFacility: 'uphc_surajpur',
    targetFacility: 'chc_dadri',
    item: 'Amoxicillin 250mg',
    quantity: 150,
    confidence: 0.91,
    reasoning: `Pediatric ward at CHC Dadri needs antibiotics. UPHC Surajpur has excess stock.`,
    timestamp: new Date().toISOString(),
  },
  {
    id: 'rec5',
    title: 'Azithromycin Re-stocking',
    sourceFacility: 'chc_bisrakh',
    targetFacility: 'uphc_harola',
    item: 'Azithromycin 500mg',
    quantity: 100,
    confidence: 0.85,
    reasoning: `UPHC Harola is running low on broad-spectrum antibiotics. Transfer from Bisrakh recommended.`,
    timestamp: new Date().toISOString(),
  }
];

// Active transfers (approved recommendations)
export interface TransferOrder {
  id: string;
  recommendationId?: string;
  sourceFacilityId: string;
  targetFacilityId: string;
  medicineId: string;
  medicineName: string;
  quantity: number;
  status: 'PENDING' | 'EN_ROUTE' | 'DELIVERED';
  timestamp: string;
}

export let localTransfers: TransferOrder[] = [];

// Helper functions to update state
export const updateLocalPHC = (updated: PHC) => {
  localPHCs = localPHCs.map((p) => (p.id === updated.id ? updated : p));
};

export const addLocalAttendance = (record: AttendanceRecord) => {
  localAttendance.push(record);
};

export const updateLocalMedicine = (updated: MedicineStock) => {
  localMedicines = localMedicines.map((m) => (m.id === updated.id ? updated : m));
};

export const updateLocalAlert = (updated: AlertItem) => {
  localAlerts = localAlerts.map((a) => (a.id === updated.id ? updated : a));
};

export const addLocalNotification = (notif: NotificationItem) => {
  localNotifications.unshift(notif);
};

export const addLocalTransfer = (transfer: TransferOrder) => {
  localTransfers.push(transfer);
};

export const updateLocalTransferStatus = (id: string, status: 'PENDING' | 'EN_ROUTE' | 'DELIVERED') => {
  localTransfers = localTransfers.map((t) => (t.id === id ? { ...t, status } : t));
};

export const removeLocalRecommendation = (id: string) => {
  localRecommendations = localRecommendations.filter((r) => r.id !== id);
};
