import { AlertItem } from '@/shared/types/alert';


export const dummyAlerts: AlertItem[] = [
  {
    id: 'a1',
    title: 'Dengue Surge Warning',
    type: 'OUTBREAK',
    priority: 'CRITICAL',
    facilityId: 'phc_badalpur',
    facilityName: 'PHC Badalpur',
    description: 'Dengue cases have increased by 150% in the last 7 days.',
    timestamp: '2026-06-29T10:00:00Z',
    resolved: false,
  },
  {
    id: 'a2',
    title: 'Malaria Cluster Detected',
    type: 'OUTBREAK',
    priority: 'HIGH',
    facilityId: 'phc_barola',
    facilityName: 'PHC Barola',
    description: 'A new cluster of 15 Malaria cases detected in Sector 49.',
    timestamp: '2026-06-29T11:00:00Z',
    resolved: false,
  },
  {
    id: 'a3',
    title: 'Typhoid Warning',
    type: 'OUTBREAK',
    priority: 'MEDIUM',
    facilityId: 'chc_bhangel',
    facilityName: 'CHC Bhangel',
    description: 'Increasing reports of water-borne Typhoid cases in Bhangel village.',
    timestamp: '2026-06-29T12:30:00Z',
    resolved: false,
  },
  {
    id: 'a4',
    title: 'Viral Fever Outbreak',
    type: 'OUTBREAK',
    priority: 'CRITICAL',
    facilityId: 'chc_dadri',
    facilityName: 'CHC Dadri',
    description: 'Over 200 pediatric viral fever cases reported in 3 days.',
    timestamp: '2026-06-29T14:15:00Z',
    resolved: false,
  },
  {
    id: 'a5',
    title: 'Acute Diarrheal Disease Warning',
    type: 'OUTBREAK',
    priority: 'HIGH',
    facilityId: 'uphc_surajpur',
    facilityName: 'UPHC Surajpur',
    description: 'Surge in ADD cases traced to contaminated local water supply.',
    timestamp: '2026-06-29T15:45:00Z',
    resolved: false,
  },
  {
    id: 'a6',
    title: 'Paracetamol Shortage',
    type: 'SHORTAGE',
    priority: 'CRITICAL',
    facilityId: 'phc_badalpur',
    facilityName: 'PHC Badalpur',
    description: 'Paracetamol stock is below critical reserve.',
    timestamp: '2026-06-29T08:30:00Z',
    resolved: false,
  },
  {
    id: 'a7',
    title: 'Dengue NS1 Kit Shortage',
    type: 'SHORTAGE',
    priority: 'HIGH',
    facilityId: 'phc_barola',
    facilityName: 'PHC Barola',
    description: 'Dengue testing kits critically low due to ongoing outbreak testing.',
    timestamp: '2026-06-29T09:15:00Z',
    resolved: false,
  },
  {
    id: 'a8',
    title: 'IV Fluids Shortage',
    type: 'SHORTAGE',
    priority: 'MEDIUM',
    facilityId: 'chc_bhangel',
    facilityName: 'CHC Bhangel',
    description: 'Normal Saline and RL stocks are depleting faster than usual.',
    timestamp: '2026-06-29T10:45:00Z',
    resolved: false,
  },
  {
    id: 'a9',
    title: 'Amoxicillin Shortage',
    type: 'SHORTAGE',
    priority: 'CRITICAL',
    facilityId: 'chc_dadri',
    facilityName: 'CHC Dadri',
    description: 'Antibiotic reserves exhausted for pediatric ward.',
    timestamp: '2026-06-29T11:20:00Z',
    resolved: false,
  },
  {
    id: 'a10',
    title: 'Azithromycin Shortage',
    type: 'SHORTAGE',
    priority: 'HIGH',
    facilityId: 'uphc_harola',
    facilityName: 'UPHC Harola',
    description: 'Limited stock of broad-spectrum antibiotics remaining.',
    timestamp: '2026-06-29T13:00:00Z',
    resolved: false,
  },
];

export default dummyAlerts;
