import { MedicineStock } from '@/shared/types/medicine';

export const dummyMedicines: MedicineStock[] = [
  {
    id: 'm1',
    name: 'Paracetamol 650mg',
    type: 'ANALGESICS',
    currentStock: 120,
    minRequiredStock: 500,
    unit: 'Strips',
    facilityId: 'phc_kalan',
  },
  {
    id: 'm2',
    name: 'ORS (Oral Rehydration Salt)',
    type: 'EMERGENCY',
    currentStock: 800,
    minRequiredStock: 1200,
    unit: 'Sachets',
    facilityId: 'phc_kalan',
  },
  {
    id: 'm3',
    name: 'Amoxicillin 250mg',
    type: 'ANTIBIOTICS',
    currentStock: 600,
    minRequiredStock: 1000,
    unit: 'Tablets',
    facilityId: 'phc_kalan',
  },
  {
    id: 'm4',
    name: 'Ibuprofen 400mg',
    type: 'ANALGESICS',
    currentStock: 280,
    minRequiredStock: 800,
    unit: 'Tablets',
    facilityId: 'phc_kalan',
  },
  {
    id: 'm5',
    name: 'Metronidazole 400mg',
    type: 'ANTIBIOTICS',
    currentStock: 450,
    minRequiredStock: 600,
    unit: 'Tablets',
    facilityId: 'phc_kalan',
  },
  {
    id: 'm6',
    name: 'Chloroquine 250mg',
    type: 'EMERGENCY',
    currentStock: 50,
    minRequiredStock: 300,
    unit: 'Tablets',
    facilityId: 'phc_kalan',
  },
  {
    id: 'm7',
    name: 'Artemether Injection',
    type: 'EMERGENCY',
    currentStock: 20,
    minRequiredStock: 100,
    unit: 'Vials',
    facilityId: 'phc_kalan',
  },
  {
    id: 'm8',
    name: 'Ciprofloxacin 500mg',
    type: 'ANTIBIOTICS',
    currentStock: 150,
    minRequiredStock: 400,
    unit: 'Tablets',
    facilityId: 'phc_kalan',
  },
  {
    id: 'm9',
    name: 'IV Fluids (Normal Saline)',
    type: 'EMERGENCY',
    currentStock: 30,
    minRequiredStock: 200,
    unit: 'Bottles',
    facilityId: 'phc_kalan',
  },
  {
    id: 'm10',
    name: 'Azithromycin 500mg',
    type: 'ANTIBIOTICS',
    currentStock: 85,
    minRequiredStock: 250,
    unit: 'Tablets',
    facilityId: 'phc_kalan',
  }
];
